server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: delivery
          uri: http://localhost:8081
          predicates:
            - Path=/deliveries/** 
        - id: order
          uri: http://localhost:8082
          predicates:
            - Path=/orders/** 
        - id: payment
          uri: http://localhost:8083
          predicates:
            - Path=/payments/** 
        - id: orderDetail
          uri: http://localhost:8084
          predicates:
            - Path= 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
        
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: pet
          uri: http://pet:8080
          predicates:
            - Path=/pets/**, /cats/**, /dogs/** 
        - id: store
          uri: http://store:8080
          predicates:
            - Path=/cartItems/**, /customers/**, /items/**
        
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
