apiVersion: v1
kind: Service
metadata:
  #서비스 이름
  name: mysql-nodeport
spec:
  ports:
    #기본적으로 그리고 편의상 'targetPort'는
    #'port' 필드와 동일한 값으로 설정된다.
    #즉 nodePort로 설정한 30003포트로 요청이 들어오면
    #3306포트로 연결시켜준다는 것이다.
    - port: 3306
      #내부에 있는 컨테이너를 연결해주기 위하여 3306포트를 사용하는 것이다.
      targetPort: 3306

      #고정 포트(NodePort)로 각 노드의 IP에 서비스를 노출시킨다.
      #NodePort 서비스가 라우팅되는 ClusterIP 서비스가 자동으로 생성된다.
      #<NodeIP>:<NodePort>를 요청하여, 클러스터 외부에서 NodePort 서비스에 접속할 수 있다.
      #즉 워커노드의 특정 포트를 열고(nodePort) 여기로 오는
      #모든 요청을 노드포트 서비스로 전달하고 노드포트 서비스는
      #해당 업무를 처리할 수 잇는 파드로 요청을 전달한다.
      #노드에 오픈할 Port를 지정하는 것이다(미지정시 30000-32768 중에 자동 할당된다.)
      #외부에 노드포트로 expose하기 위해 30000번 포트를 지정한다.
      #이것은 expose 명령으로도 대체가 가능하나 이 30000번은 쓸 수 없다.
      nodePort: 30000
  selector:
    app: mysql

  #서비스 타입을 설정
  type: NodePort